apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - env-vars.env
  name: authorino-operator-env

images:
- name: controller
  newName: quay.io/kuadrant/authorino-operator
  newTag: latest
