apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authorino-set-superseding-host-subsets
rules:
  - apiGroups: ["operator.authorino.kuadrant.io"]
    resources: ["authorinos"]
    verbs: ["set-superseding-host-subsets"]
