apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhooks-manager-role
rules:
- apiGroups:
  - authorino.kuadrant.io
  resources:
  - authconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorino.kuadrant.io
  resources:
  - authconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: system
  name: webhooks-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authorino-webhooks-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: SERVICE_NAMESPACE
