apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restrict-spec-fields.yaml
  - restrict-all-namespaces.yaml
  - set-privileged-fields-role.yaml
  - set-cluster-wide-role.yaml
