# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authconfigs.authorino.kuadrant.io
  annotations:
    cert-manager.io/inject-ca-from: WEBHOOK_CERTIFICATE_NAMESPACE/WEBHOOK_CERTIFICATE_NAME
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: WEBHOOK_SERVICE_NAMESPACE
          name: WEBHOOK_SERVICE_NAME
          path: /convert
      conversionReviewVersions:
      - v1beta1
      - v1beta2
