name: Scheduled build with latest image SHA versions

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yaml
    secrets: inherit
    with:
      operatorVersion: ${{ github.sha }}
      operatorTag: ${{ github.sha }}
      authorinoVersion: ${{ vars.AUTHORINO_SHA != '' && vars.AUTHORINO_SHA || 'latest' }}
      channels: stable
      defaultChannel: stable
∑